"use client";

import { isReservedSlug, isValidSlug } from "@critichut/db/schema";
import { Input } from "@critichut/ui/input";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  Cancel01Icon,
  Loading03Icon,
  Tick01Icon,
} from "@hugeicons-pro/core-bulk-rounded";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { authClient } from "~/auth/client";
import { useWizard } from "./wizard-context";

// Helper to generate slug from string
const generateSlug = (text: string): string => {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-") // Replace non-alphanumeric chars with hyphens
    .replace(/^-+|-+$/g, "") // Remove leading/trailing hyphens
    .substring(0, 40); // Limit length
};

export function StepSubdomain() {
  const { slug, setSlug, organizationName, website, setValidationError } =
    useWizard();
  const [debouncedSlug, setDebouncedSlug] = useState(slug);
  const [error, setError] = useState("");
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);

  // Auto-generate slug on first load if empty, prioritizing organization name then website domain
  useEffect(() => {
    if (!(slug || isAutoGenerated)) {
      let newSlug = "";
      if (organizationName) {
        newSlug = generateSlug(organizationName);
      } else if (website) {
        try {
          // Extract domain name without TLD if possible, or just use full domain
          const hostname = new URL(
            website.startsWith("http") ? website : `https://${website}`
          ).hostname;
          const parts = hostname.split(".");
          // Use the part before the TLD (e.g., "google" from "google.com" or "sub" from "sub.domain.com")
          // Simple heuristic: take the second to last part if > 2 parts, or first part
          newSlug = generateSlug(
            parts.length > 1 ? (parts.at(-2) ?? hostname) : hostname
          );
        } catch {
          // Invalid website URL, ignore
        }
      }

      if (newSlug) {
        setSlug(newSlug);
        setIsAutoGenerated(true);
      }
    }
  }, [slug, organizationName, website, setSlug, isAutoGenerated]);

  // Debounce slug for API calls
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSlug(slug);
    }, 300);
    return () => clearTimeout(timer);
  }, [slug]);

  const { data, isLoading } = useQuery({
    queryKey: ["checkSlug", debouncedSlug],
    queryFn: async () => {
      const result = await authClient.organization.checkSlug({
        slug: debouncedSlug,
      });
      return result.data;
    },
    enabled: Boolean(
      debouncedSlug &&
        debouncedSlug.length >= 3 &&
        isValidSlug(debouncedSlug) &&
        !isReservedSlug(debouncedSlug)
    ),
  });

  // Validate format and update global validation state
  useEffect(() => {
    let currentError = "";

    if (!slug || slug.length < 3) {
      // Don't show error immediately if empty, but block next
      // currentError = "Subdomain must be at least 3 characters";
    } else if (!isValidSlug(slug)) {
      currentError =
        "Slug can only contain lowercase letters, numbers, and hyphens";
    } else if (isReservedSlug(slug)) {
      currentError = "This slug is reserved and cannot be used";
    } else if (data && !data.status) {
      currentError = "This subdomain is already taken";
    }

    setError(currentError);

    // Update global validation state for the layout button
    const isValid =
      slug &&
      slug.length >= 3 &&
      isValidSlug(slug) &&
      !isReservedSlug(slug) &&
      data?.status &&
      !isLoading;

    setValidationError(isValid ? null : "Invalid subdomain");
  }, [slug, data, isLoading, setValidationError]);

  const handleChange = (value: string) => {
    setSlug(value.toLowerCase());
    // Manual change overrides auto-generation logic
    setIsAutoGenerated(true);
  };

  const isAvailable = data?.status === true;

  return (
    <>
      <div className="w-full max-w-md space-y-6">
        <div>
          <h1 className="mb-2 font-bold text-2xl">Pick a subdomain</h1>
          <p className="text-muted-foreground">
            Choose a unique subdomain for your feedback board
          </p>
        </div>

        <div>
          <div className="flex rounded-md shadow-xs">
            <Input
              className="-me-px rounded-e-none shadow-none focus-visible:z-10"
              onChange={(e) => handleChange(e.target.value)}
              placeholder="acme-inc"
              type="text"
              value={slug}
            />
            <span className="inline-flex items-center rounded-e-md border border-input bg-input/30 px-3 text-muted-foreground text-sm">
              .critichut.com
            </span>
          </div>

          {/* Status Icons - Positioned differently now or maybe inside the input? 
              The requested design doesn't show where icons go. 
              Putting them to the right of the addon might look weird.
              Maybe absolutely positioned inside the Input but with padding-right adjusted?
              Or status text below.
          */}
          <div className="mt-2 flex min-h-[20px] items-center gap-2">
            {isLoading && (
              <>
                <HugeiconsIcon
                  className="animate-spin"
                  icon={Loading03Icon}
                  size={16}
                />
                <span className="text-muted-foreground text-xs">
                  Checking availability...
                </span>
              </>
            )}
            {!isLoading && isAvailable && slug.length >= 3 && (
              <>
                <HugeiconsIcon
                  className="text-green-600"
                  icon={Tick01Icon}
                  size={16}
                />
                <span className="text-green-600 text-xs">
                  Subdomain is available
                </span>
              </>
            )}
            {!isLoading &&
              (error || (data && !isAvailable)) &&
              slug.length > 0 && (
                <>
                  <HugeiconsIcon
                    className="text-destructive"
                    icon={Cancel01Icon}
                    size={16}
                  />
                  <span className="text-destructive text-xs">
                    {error || "This subdomain is already taken"}
                  </span>
                </>
              )}
          </div>
        </div>
      </div>
      {/* Footer buttons are now handled by WizardLayout via context validation state */}
    </>
  );
}
